const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  await prisma.movie.createMany({
    data: [
      // Original 10 movies...
      {
        title: "Inception",
        type: "Movie",
        director: "Christopher Nolan",
        actors: "Leonardo DiCaprio, Joseph Gordon-Levitt",
        genre: "Sci-Fi, Thriller",
        boxOffice: 829895144,
        budget: 160000000,
        location: "USA",
        duration: "1h48m",
        year: "2010",
      },
      {
        title: "The Dark Knight",
        type: "Movie",
        director: "Christopher Nolan",
        actors: "Christian Bale, Heath Ledger",
        genre: "Action, Crime",
        boxOffice: 1004558444,
        budget: 185000000,
        location: "USA",
        duration: "1h52m",
        year: "2008",
      },
      {
        title: "Interstellar",
        type: "Movie",
        director: "Christopher Nolan",
        actors: "Matthew McConaughey, Anne Hathaway",
        genre: "Sci-Fi, Drama",
        boxOffice: 677471339,
        budget: 165000000,
        location: "USA",
        duration: "1h43m",
        year: "2014",
      },
      {
        title: "Avengers: Endgame",
        type: "Movie",
        director: "Anthony and Joe Russo",
        actors: "Robert Downey Jr., Chris Evans",
        genre: "Action, Sci-Fi",
        boxOffice: 2797501328,
        budget: 356000000,
        location: "USA",
        duration: "1h51m",
        year: "2019",
      },
      {
        title: "Parasite",
        type: "Movie",
        director: "Bong Joon-ho",
        actors: "Song Kang-ho, Lee Sun-kyun",
        genre: "Drama, Thriller",
        boxOffice: 263147056,
        budget: 11400000,
        location: "South Korea",
        duration: "1h32m",
        year: "2019",
      },
      {
        title: "Joker",
        type: "Movie",
        director: "Todd Phillips",
        actors: "Joaquin Phoenix, Robert De Niro",
        genre: "Crime, Drama",
        boxOffice: 1074251311,
        budget: 55000000,
        location: "USA",
        duration: "1h22m",
        year: "2019",
      },
      {
        title: "Titanic",
        type: "Movie",
        director: "James Cameron",
        actors: "Leonardo DiCaprio, Kate Winslet",
        genre: "Romance, Drama",
        boxOffice: 2216472647,
        budget: 200000000,
        location: "USA",
        duration: "1h39m",
        year: "1997",
      },
      {
        title: "The Matrix",
        type: "Movie",
        director: "The Wachowskis",
        actors: "Keanu Reeves, Laurence Fishburne",
        genre: "Sci-Fi, Action",
        boxOffice: 466364845,
        budget: 63000000,
        location: "USA",
        duration: "1h36m",
        year: "1999",
      },
      {
        title: "Gladiator",
        type: "Movie",
        director: "Ridley Scott",
        actors: "Russell Crowe, Joaquin Phoenix",
        genre: "Action, Drama",
        boxOffice: 503200000,
        budget: 103000000,
        location: "USA",
        duration: "1h55m",
        year: "2000",
      },
      {
        title: "The Godfather",
        type: "Movie",
        director: "Francis Ford Coppola",
        actors: "Marlon Brando, Al Pacino",
        genre: "Crime, Drama",
        boxOffice: 250000000,
        budget: 6000000,
        location: "USA",
        duration: "1h75m",
        year: "1972",
      },

      // 15 more movies
      {
        title: "Forrest Gump",
        type: "Movie",
        director: "Robert Zemeckis",
        actors: "Tom Hanks, Robin Wright",
        genre: "Drama, Romance",
        boxOffice: 678226465,
        budget: 55000000,
        location: "USA",
        duration: "1h42m",
        year: "1994",
      },
      {
        title: "The Revenant",
        type: "Movie",
        director: "Alejandro G. Iñárritu",
        actors: "Leonardo DiCaprio, Tom Hardy",
        genre: "Adventure, Drama",
        boxOffice: 533000000,
        budget: 135000000,
        location: "Canada",
        duration: "1h56m",
        year: "2015",
      },
      {
        title: "Dunkirk",
        type: "Movie",
        director: "Christopher Nolan",
        actors: "Fionn Whitehead, Tom Hardy",
        genre: "War, Drama",
        boxOffice: 526949303,
        budget: 100000000,
        location: "UK",
        duration: "1h06m",
        year: "2017",
      },
      {
        title: "Black Panther",
        type: "Movie",
        director: "Ryan Coogler",
        actors: "Chadwick Boseman, Michael B. Jordan",
        genre: "Action, Adventure",
        boxOffice: 1346913161,
        budget: 200000000,
        location: "USA",
        duration: "1h34m",
        year: "2018",
      },
      {
        title: "Whiplash",
        type: "Movie",
        director: "Damien Chazelle",
        actors: "Miles Teller, J.K. Simmons",
        genre: "Drama, Music",
        boxOffice: 49000000,
        budget: 3300000,
        location: "USA",
        duration: "1h06m",
        year: "2014",
      },
      {
        title: "La La Land",
        type: "Movie",
        director: "Damien Chazelle",
        actors: "Ryan Gosling, Emma Stone",
        genre: "Comedy, Drama",
        boxOffice: 446100000,
        budget: 30000000,
        location: "USA",
        duration: "1h28m",
        year: "2016",
      },
      {
        title: "The Lion King",
        type: "Movie",
        director: "Jon Favreau",
        actors: "Donald Glover, Beyoncé",
        genre: "Animation, Adventure",
        boxOffice: 1656943394,
        budget: 260000000,
        location: "USA",
        duration: "1h18m",
        year: "2019",
      },
      {
        title: "Frozen",
        type: "Movie",
        director: "Chris Buck, Jennifer Lee",
        actors: "Kristen Bell, Idina Menzel",
        genre: "Animation, Adventure",
        boxOffice: 1280000000,
        budget: 150000000,
        location: "USA",
        duration: "1h02m",
        year: "2013",
      },
      {
        title: "Avatar",
        type: "Movie",
        director: "James Cameron",
        actors: "Sam Worthington, Zoe Saldana",
        genre: "Sci-Fi, Adventure",
        boxOffice: 2923706026,
        budget: 237000000,
        location: "USA",
        duration: "1h62m",
        year: "2009",
      },
      {
        title: "The Irishman",
        type: "Movie",
        director: "Martin Scorsese",
        actors: "Robert De Niro, Al Pacino",
        genre: "Crime, Drama",
        boxOffice: 8000000,
        budget: 159000000,
        location: "USA",
        duration: "2h09m",
        year: "2019",
      },
      {
        title: "1917",
        type: "Movie",
        director: "Sam Mendes",
        actors: "George MacKay, Dean-Charles Chapman",
        genre: "War, Drama",
        boxOffice: 384000000,
        budget: 95000000,
        location: "UK",
        duration: "1h19m",
        year: "2019",
      },
      {
        title: "Skyfall",
        type: "Movie",
        director: "Sam Mendes",
        actors: "Daniel Craig, Javier Bardem",
        genre: "Action, Thriller",
        boxOffice: 1108561013,
        budget: 200000000,
        location: "UK",
        duration: "1h43m",
        year: "2012",
      },
      {
        title: "The Social Network",
        type: "Movie",
        director: "David Fincher",
        actors: "Jesse Eisenberg, Andrew Garfield",
        genre: "Biography, Drama",
        boxOffice: 224920315,
        budget: 40000000,
        location: "USA",
        duration: "1h20m",
        year: "2010",
      },
      {
        title: "Shutter Island",
        type: "Movie",
        director: "Martin Scorsese",
        actors: "Leonardo DiCaprio, Mark Ruffalo",
        genre: "Mystery, Thriller",
        boxOffice: 294800000,
        budget: 80000000,
        location: "USA",
        duration: "1h38m",
        year: "2010",
      },
      {
        title: "Mad Max: Fury Road",
        type: "Movie",
        director: "George Miller",
        actors: "Tom Hardy, Charlize Theron",
        genre: "Action, Adventure",
        boxOffice: 375200000,
        budget: 150000000,
        location: "Australia",
        duration: "1h20m",
        year: "2015",
      },

      // 15 TV Shows
      {
        title: "Breaking Bad",
        type: "TV Show",
        director: "Vince Gilligan",
        actors: "Bryan Cranston, Aaron Paul",
        genre: "Crime, Drama",
        boxOffice: 0,
        budget: 3000000,
        location: "USA",
        duration: "1h49m",
        year: "2008",
      },
      {
        title: "Game of Thrones",
        type: "TV Show",
        director: "David Benioff, D.B. Weiss",
        actors: "Emilia Clarke, Kit Harington",
        genre: "Drama, Fantasy",
        boxOffice: 0,
        budget: 15000000,
        location: "USA",
        duration: "1h57m",
        year: "2011",
      },
      {
        title: "The Crown",
        type: "TV Show",
        director: "Peter Morgan",
        actors: "Claire Foy, Olivia Colman",
        genre: "Biography, Drama",
        boxOffice: 0,
        budget: 13000000,
        location: "UK",
        duration: "1h58m",
        year: "2016",
      },
      {
        title: "The Mandalorian",
        type: "TV Show",
        director: "Jon Favreau",
        actors: "Pedro Pascal, Gina Carano",
        genre: "Action, Adventure",
        boxOffice: 0,
        budget: 15000000,
        location: "USA",
        duration: "2h40m",
        year: "2019",
      },
      {
        title: "Stranger Things",
        type: "TV Show",
        director: "The Duffer Brothers",
        actors: "Millie Bobby Brown, Finn Wolfhard",
        genre: "Drama, Fantasy",
        boxOffice: 0,
        budget: 12000000,
        location: "USA",
        duration: "3h51m",
        year: "2016",
      },
      {
        title: "The Office",
        type: "TV Show",
        director: "Greg Daniels",
        actors: "Steve Carell, Rainn Wilson",
        genre: "Comedy",
        boxOffice: 0,
        budget: 2000000,
        location: "USA",
        duration: "2h27m",
        year: "2005",
      },
      {
        title: "Friends",
        type: "TV Show",
        director: "David Crane, Marta Kauffman",
        actors: "Jennifer Aniston, Courteney Cox",
        genre: "Comedy, Romance",
        boxOffice: 0,
        budget: 1000000,
        location: "USA",
        duration: "2h2m",
        year: "1994",
      },
      {
        title: "The Witcher",
        type: "TV Show",
        director: "Lauren Schmidt Hissrich",
        actors: "Henry Cavill, Anya Chalotra",
        genre: "Action, Fantasy",
        boxOffice: 0,
        budget: 10000000,
        location: "Poland",
        duration: "2h47m",
        year: "2019",
      },
      {
        title: "Dark",
        type: "TV Show",
        director: "Baran bo Odar",
        actors: "Louis Hofmann, Lisa Vicari",
        genre: "Crime, Drama",
        boxOffice: 0,
        budget: 6000000,
        location: "Germany",
        duration: "1h52m",
        year: "2017",
      },
      {
        title: "Money Heist",
        type: "TV Show",
        director: "Álex Pina",
        actors: "Úrsula Corberó, Álvaro Morte",
        genre: "Action, Crime",
        boxOffice: 0,
        budget: 2000000,
        location: "Spain",
        duration: "4h15m",
        year: "2017",
      },
      {
        title: "Loki",
        type: "TV Show",
        director: "Michael Waldron",
        actors: "Tom Hiddleston, Owen Wilson",
        genre: "Action, Sci-Fi",
        boxOffice: 0,
        budget: 25000000,
        location: "USA",
        duration: "3h52m",
        year: "2021",
      },
      {
        title: "WandaVision",
        type: "TV Show",
        director: "Jac Schaeffer",
        actors: "Elizabeth Olsen, Paul Bettany",
        genre: "Action, Comedy",
        boxOffice: 0,
        budget: 22500000,
        location: "USA",
        duration: "3h15m",
        year: "2021",
      },
      {
        title: "House of the Dragon",
        type: "TV Show",
        director: "Ryan Condal, George R.R. Martin",
        actors: "Emma D'Arcy, Matt Smith",
        genre: "Fantasy, Drama",
        boxOffice: 0,
        budget: 20000000,
        location: "USA",
        duration: "2h4m",
        year: "2022",
      },
      {
        title: "Squid Game",
        type: "TV Show",
        director: "Hwang Dong-hyuk",
        actors: "Lee Jung-jae, Park Hae-soo",
        genre: "Action, Drama",
        boxOffice: 0,
        budget: 21400000,
        location: "South Korea",
        duration: "1h34m",
        year: "2021",
      },
      {
        title: "Sherlock",
        type: "TV Show",
        director: "Mark Gatiss, Steven Moffat",
        actors: "Benedict Cumberbatch, Martin Freeman",
        genre: "Crime, Drama",
        boxOffice: 0,
        budget: 4000000,
        location: "UK",
        duration: "1h23m",
        year: "2010",
      },
    ],
  });

  console.log("✅ Seeded movie records.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => {
    prisma.$disconnect();
  });
